apiVersion: oathkeeper.ory.sh/v1alpha1
kind: Rule
metadata:
  name: helloworld-rule
spec:
  authenticators:
  - handler: noop
  authorizer:
    handler: allow
  match:
    methods:
      - GET
      - PUT
      - POST
    url: <http|https>://{{ .Values.host }}.{{ .Values.global.ingress.domainName }}<(:(80|443))?></helloworld/hello>
  upstream:
    url: http://helloworld.{{ .Values.helloworld.namespace }}.svc.cluster.local:80
    #Strip path removes "/helloworld" from the path
    stripPath: "/helloworld"
