apiVersion: oathkeeper.ory.sh/v1alpha1
kind: Rule
metadata:
  name: httpbin-rule
spec:
  authenticators:
  - handler: noop
  authorizer:
    handler: allow
  match:
    methods:
      - GET
      - PUT
      - POST
    url: <http|https>://{{ .Values.host }}.{{ .Values.global.ingress.domainName }}<(:(80|443))?></httpbin/.*>
  upstream:
    url: http://httpbin.{{ .Values.httpbin.namespace }}.svc.cluster.local:80
    #Strip path removes "/httpbin" from the path
    stripPath: "/httpbin"
