apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: poc-vs
  namespace: httpbin
spec:
  gateways:
  - {{ .Values.global.istio.gateway.namespace }}/{{ .Values.global.istio.gateway.name }}
  hosts:
  - {{ .Values.host }}.{{ .Values.global.ingress.domainName }}
  http:
  - corsPolicy:
      allowHeaders:
      - Authorization
      - Content-Type
      - X-Broker-API-Version
      allowMethods: ["GET", "PUT", "POST"]
      allowOrigins:
      - regex: ".*"
    match:
    - uri:
        regex: /httpbin/.*
    route:
    - destination:
        host: {{ .Values.global.oathkeeper.host }}
        port:
          number: {{ .Values.global.oathkeeper.port }}
  - corsPolicy:
      allowHeaders:
      - Authorization
      - Content-Type
      - X-Broker-API-Version
      allowMethods: ["GET", "PUT", "POST"]
      allowOrigins:
      - regex: ".*"
    match:
    - uri:
        regex: /helloworld/.*
    route:
    - destination:
        host: {{ .Values.global.oathkeeper.host }}
        port:
          number: {{ .Values.global.oathkeeper.port }}