httpbin:
  namespace: httpbin

helloworld:
  namespace: hello-world

host: test-host

global:
  ingress:
    domainName: cluster.project.shoot.canary.k8s-hana.ondemand.com
  istio:
    gateway:
      namespace: kyma-system
      name: kyma-gateway
  oathkeeper:
    host: ory-oathkeeper-proxy.kyma-system.svc.cluster.local
    port: 4455
